version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "secret-pw"
      MYSQL_DATABASE: "desafio"
    ports:
      - "3306:3306"
    volumes:
      - ~/desafio/docker/volumes:/var/lib/mysql
      - ~/desafio/docker/scripts/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - mysql-network
    healthcheck:
      test:  mysql --user=root --password=secret-pw -e 'select * from desafio.car' desafio

  adminer:
    image: adminer
    network_mode: host
  
  desafio-volanty:
    image: biapcampos/volanty-projeto-desafio:1.0.1
    network_mode: host
    depends_on:
      - mysql
    restart: on-failure

networks:
  mysql-network:
    driver: bridge
  
